apiVersion: stork.libopenstorage.org/v1alpha1
kind: MigrationSchedule
metadata:
  name: migrationschedule-postgres-failover-no-test
  namespace: kube-system
spec:
  template:
    spec:
      clusterPair: replication-cluster-pair
      includeResources: true #Replicate K8s Objects
      startApplications: false #Won't scale up pod replicas
      includeVolumes: true #Replicate volumes
      namespaces:
      - postgres
  schedulePolicyName: every-15-mins #The recent step
  suspend: false #Won't stop after first replication try
  autoSuspend: true #Stop replication if bound and scaling actions happened on destination cluster
